sudo: false
os: linux

before_install:
  # osx on travis doesn't support sbt, so install it
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
      brew install sbt;
    fi
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test publishLocal

# Note: OSX has issues with oraclejdk8
# see https://github.com/travis-ci/travis-ci/issues/2316
matrix:
  include:
    - jdk: oraclejdk8
      language: scala
      scala: 2.12.8
    - jdk: oraclejdk8
      language: scala
      scala: 2.13.0
    - jdk: oraclejdk11
      language: scala
      scala: 2.13.0
    - os: osx
      osx_image: xcode9.3
      language: java
      env:
        - TRAVIS_SCALA_VERSION=2.13.0
    - os: osx
      osx_image: xcode10.1
      language: java
      env:
        - TRAVIS_SCALA_VERSION=2.13.0
cache:
  directories:
    - "$HOME/.ivy2/cache"
before_cache:
  - rm -rf $HOME/.ivy2/cache/io.methvin/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/io.methvin/*
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
